# -*- coding: utf-8 -*-
"""SoC_Week1_Assg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1Kvj0Rty1kxKSoAEzxIuZE8hiNGvRWp

1. Leaders in an array
"""

import numpy as np

input = [16, 17, 4, 3, 5, 2]
leaders = []

for i in range(len(input)):
  count = 0
  for j in range(len(input)):
    if j>i:
      if input[i] > input[j]:
        count = count + 1
      else:
        break
    else:
      count = count
  if count == len(input) - i - 1:
    leaders.append(input[i])
    
leaders

"""2. Trapping Rain Water

"""

a = [3,0,0,2,0,4]
height = min(a[0], a[len(a)-1])
vol = height*(len(a)-2)

for i in range(1, len(a)-1):
  if(a[i]<height):
    vol = vol - a[i]
  else:
    vol = vol - height

vol

"""3. Minimum Platforms (Not to be considered, attempted as optional)

"""

a = [900, 940, 950, 1100, 1500, 1800]
d = [910, 1200, 1120, 1130, 1900, 2000]
count = 0                                # We'll be counting number of platforms using this variable. 

for i in range(len(a)):
  for j in range(len(a)):
    if j<i:
      if(a[i]>d[j]):
        count = count
      else:
        count = count + 1
        break 
    else:
       break

count

"""4. Reverse a String

"""

txt = "Findmeout"[::-1]
print(txt)

"""5. Palindrome String

"""

s = "abba"
t = s[::-1]
if s==t:
    print(1)
else:
    print(0)